### PR TITLE
Expand setup.py information

### PR DESCRIPTION
**Pull request by MartinThoma**
- Add supported Python version (Python 2.7)
- Add license (GPLv2+)
- Add keywords (diff, merge)

### CODE REVIEW

**Comment by kaiw** [comment]
Unfortunately because this is just a mirror repository, I can't actually do anything with the pull request, but your patch is now in master. Thanks.

**Comment by MartinThoma** [comment]
@kaiw What would be the correct way to suggest changes?

**Comment by kaiw** [comment]
@MartinThoma You can send patches to the [mailing list](https://mail.gnome.org/mailman/listinfo/meld-list) or file a bug in [bugzilla](https://bugzilla.gnome.org). However, I do watch this repo just so that I can pull in patches from github PRs, so for simple patches it's really fine either way.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to meld!

meld uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
