### PR TITLE
Mention where to file issues

### PR DESCRIPTION
**Pull request by dandv**

### CODE REVIEW

**Comment by gnomesysadmins** [comment]
Thank you for contributing to meld!

meld uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers
and follow the instructions there to upload your change to Bugzilla.

**Comment by dandv** [comment]
@kaiw: `meld uses Bugzilla...`, sure, but do realize that the vast majority of GitHub users *don't* use it, and it would help to point them to where they can contribute issues or fixes.

**Comment by kaiw** [comment]
...and you want to fix this by opening *two* fake PRs and then @-ing me in a conversation you're having with a bot, in a mirror repo that I have no control over? Come on.

In the current `README` there's a link to the mailing list (where you can contribute fixes) and the main site that has a "Development" page (that tells you where to send bugs and contribute patches). If you'd like to suggest how we could add another useful link in the `README` list then please do, keeping in mind that Bugzilla doesn't have a single page overview for a project that lets you both easily see bugs and file new ones.

**Comment by dandv** [comment]
> ...and you want to fix this by opening two fake PRs and then @-ing me in a conversation you're having with a bot, in a mirror repo that I have no control over? Come on.

I've done that because the Issues tab is disabled and the contribution process was completely ignorant of GitHub users, treating GitHub as merely a mirror for the GNOME repo. There are actual developers here, who care, but perhaps not above the [PITA threshold](https://wiki.dandascalescu.com/essays/pita-threshold) - a concept introduced to me in 2009 by the GitHub founders, which has proven surprisingly valuables since, and which played a critical role in enabling them to overtake Google Code, CPAN's development process, and pretty much all other other more cumbersome contribution processes.

With this "fake PR" I've attempted to ease the contribution process and reduce that PITA threshold.

Unfortunately, that wasn't well received, and on top of that I've found some serious enough issues with Meld to be discouraged from trying to contribute any further.

As a parting gift, perhaps: I've found that Meld suffers from horrible performance issues, taking minutes to compare two 50k-line CSV files, which [other tools](http://www.grigsoft.com/wincmp3.htm) compare in under 2 seconds (via Wine). Worse, the comparison result was completely off:

image
image

If this were a GitHub-user-friendly project, I'd be happy to put in the effort to scrub those files of sensitive data and contribute [one more bug report](https://wiki.dandascalescu.com/bugs), along with the minimal test case that reproduced the behavior from the screenshot. Or at least if there were some link to the issue tracker for Meld.

**Comment by kaiw** [comment]
> treating GitHub as merely a mirror for the GNOME repo

GitHub *is* merely a mirror for the GNOME repo, and not one that I have any control over, as I've already pointed out.

> With this "fake PR" I've attempted to ease the contribution process and reduce that PITA threshold.

No, you haven't. You can't possibly think that either of those PRs were going to be merged, since neither of them tells contributors anything of value. I've already suggested a fix, but you decided instead to lecture me about contributor processes and include half of a useless bug report.

Normally, I'd drop this whole thing as a bad joke, but I feel like it's important that you appreciate that the attitude you've displayed here comes across as being actively hostile to FOSS communities that don't live on Github. I feel like a "Developer Advocate" should understand that demanding that a free software project use tooling and processes that match your personal preference is likely to be seen as coercive and petty.

I'll probably end up adding a link to Bugzilla in the `README` at some point, because I don't intend to let the obnoxious nature of this PR get in the way of making an actual improvement.

**Comment by dandv** [comment]
I do apologize for my approach. I understand that the GitHub repo is a mirror, and was trying to point out that the GitHub *contributors* might deserve a bit more attention. The link to Bugzilla is what I was after, and I should've searched for it and submitted a PR against the README.

A PR was the only way I saw to draw someone's attention to the repo. Of course I didn't expect it to be merged, but it's a technique I've used in the past on repos without the Issues tab. I even got lucky one time :)

image

**Comment by kaiw** [comment]
Thanks.

I've updated the README somewhat. It's not great, but hopefully it'll make it a bit clearer about where existing infrastructure is.

**Comment by dandv** [comment]
Thank you. I've filed a [hopefully more useful bug report](https://bugzilla.gnome.org/show_bug.cgi?id=784306) too.

**Pull request closed without merging**
